#!/usr/bin/env python
import web
import json
from pprint import pprint

urls = (
    '/users', 'list_users',
    '/users/(.*)', 'get_user'
)

app = web.application(urls, globals())

class list_users:        
    def GET(self):
        with open('user_data.json') as data_file:    
            data = json.load(data_file)
        return data

class get_user:
    def GET(self, user):
        with open('user_data.json') as data_file:    
            data = json.load(data_file)
        return data[user]

if __name__ == "__main__":
    app.run()
